version: '3.9'
services:
  mongo_db:
    container_name: mongo_70105
    image: mongo:latest
    ports:
      - 27025:27017
    # volumes:
    #   - /d/DOCKER/MONGO/mongo_70105:/data/db

  api:
    container_name: api_70105
    build: .
    ports:
      - 8085:8080
    environment:
      # - mongodb://mongo_70105:27017/coderhouse
      - mongodb+srv://admin:admin@cluster0.xibok.mongodb.net/coderhouse?retryWrites=true&w=majority
